/**
 * TESTING 
 * 
 * WHY IS IMPORTANT TESTING: 
 * 
 * DEBUG 
 * ASOLATING COMPONENT 
 * TEST INPUT VALIDATION 
 * THROW ERROR
 * CATCH ERROR
 * TEST DRIVEN DEVELOPMENT 
 *  WRITE THE TEST FIRST THEN WROTE THE CODE SECOND 
 *      MAKE IT FIRST FAIL THEN MAKE IT WORK 
 * UNIT TESTING 
 * 
 * JASMINE
 * 
 * JASMINE IS A POPULAR TESTING FRAMEWORK FOR JAVASCRIPT
 * 
 * will create a package 
 * npn init -y  
 * **/